### ISSUE TITLE
Browser back button quirk

### ISSUE THREAD

**Issue by sasindumendis** [Sebmaster/nests-for-trello#2]
When land on a board by clicking a card linked to it, you cannot use the browser back button as usual (clicking once) to go back, you re trapped in a redirect loop on current page. But the history does get recorded, which means you can right click or  click and hold to see the recent history and go back.

**Comment by sasindumendis** [comment]
Ideally the best solution is to figure out how Trello do this linking stuff and fix it so that we dont have to think about the best way to implement a going back mechanism. However only worth it if it wouldnt eat up a lot of time.

Next option is maybe adding a simple back button hack with a `history.go(-2)` (havent tested either this work or -2 is always the correct value)

Having a breadcrumb (like so: fromboard > thisboard ) also came to my mind. But that will complicate things. And specially at least in my case I m not useing Trellonest to link boards in a fully hierarchical way, but rather to hyperlink.

**Comment by Sebmaster** [comment]
The idea to fix this would request board info from the API onclick and then directly redirect to the full url (given by the API). I'm on it.
